package saps.archiver.interfaces;

import java.util.Collection;


public interface Archiver {

    /**
    * It deletes from the temporary storage the data generated by {@code ImageTaskState.FAILED}
    * tasks.
    */
    Collection<SapsImage> gc();

    /**
    * It tries archiving {@code ImageTaskState.FINISHED} {@code SapsImage} in {@code
    * PermanentStorage}. When archiving fails, the {@code SapsImage} moves to FAILED
    */
    Collection<SapsImage> archive();

}