package main.java.interfaces;

public interface Archiver {

    /**
    It start the main (and single) Thread to run gc() and tryArchive()
    peridocally, with a fixed time delay.
    */
    public void start();

    /**
    * It deletes from the temporary storage the data generated by {@code ImageTaskState.FAILED}
    * tasks.
    */
    public void gc();

    /**
    * It tries archiving {@code ImageTaskState.FINISHED} {@code SapsImage} in {@code
    * PermanentStorage}. When archiving fails, the {@code SapsImage} moves to FAILED
    */
    public void tryArchive();

}